---
kind: pipeline
name: default

clone:
  depth: 50

steps:
  - name: build
    image: golang:1.13
    commands:
      - go test -v ./...

  - name: lint
    image: golangci/golangci-lint:v1.22.2
    commands:
      - golangci-lint run -v
