---
kind: pipeline
name: default

clone:
  depth: 50

steps:
  - name: build
    image: golang:1.16
    commands:
      - go test -v ./...

  - name: lint
    image: golangci/golangci-lint:v1.27.0
    commands:
      - golangci-lint run -v
